In [1]:
import pandas as pd
import numpy as np
np.random.seed(42)
n_rows = 1000
data = {"color":np.random.choice(['red','blue','green'],n_rows),
        "size":np.random.choice(['small','medium','large'],n_rows),
        "material":np.random.choice(['plastic','metal','wood'],n_rows),
        "price":np.random.randint(10,500,n_rows)}

df=pd.DataFrame(data)

In [2]:
df

     color    size material  price
0    green   large    metal    423
1      red   large  plastic    351
2    green   large  plastic    229
3    green   large     wood    400
4      red   small  plastic    172
..     ...     ...      ...    ...
995   blue   small     wood    286
996   blue   large  plastic    473
997  green  medium  plastic    213
998  green   large    metal    203
999    red   large    metal    178

[1000 rows x 4 columns]

In [3]:
%pip install category_encoders

Requirement already satisfied: category_encoders in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (from category_encoders) (2.3.3)
Requirement already satisfied: pandas>=1.0.5 in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (from category_encoders) (2.2.3)
Requirement already satisfied: patsy>=0.5.1 in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (from category_encoders) (1.6.0)
Requirement already satisfied: scipy>=1.0.0 in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (from category_encoders) (1.17.1)
Requirement already satisfied: statsmodels>=0.9.0 in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=1.0.5->category_encoders) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=1.0.5->category_encoders) (2024.2)
Requirement already satisfied: six>=1.5 in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in c:\Users\AVANIY\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsmodels>=0.9.0->category_encoders) (24.2)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [5]:
x = df.drop(columns='price')
y = df.price
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8 , random_state=42)

In [6]:
label_encoder = LabelEncoder()
'''


'''

'\n\n\n'

In [7]:
label_encoder.fit_transform(xtrain['color'])  #accepts only 1 col

array([1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 2, 0, 1,
       2, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 1, 1, 0, 2, 1,
       2, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2,
       1, 1, 2, 2, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 2, 1, 2,
       2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 2, 1,
       2, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 0, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1,
       2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 1, 1, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 0, 2, 1,
       0, 0, 0, 1, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 1, 2, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0, 1, 2,
       1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 1, 2, 2, 0, 0, 2, 2, 2, 2, 0,
       0, 2, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2, 2, 1, 2, 1, 2, 0, 0, 2, 1,
       1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 2, 1, 2, 1, 0, 0, 1, 0, 2, 1, 1, 1, 2, 1, 2, 0, 1, 2, 1, 2, 0,
       2, 2, 0, 1, 1, 0, 2, 0, 0, 2, 2, 0, 0, 2, 2, 2, 1, 0, 1, 0, 0, 2,
       0, 2, 2, 2, 0, 2, 0, 1, 1, 2, 2, 0, 1, 0, 2, 2, 1, 2, 2, 2, 1, 1,
       2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 2,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 2, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 2, 2, 0, 1, 1, 2, 2, 0, 2, 2, 1, 1, 1, 1, 0, 2, 1,
       0, 1, 0, 2, 2, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 0, 2, 2, 0, 2, 2, 1,
       1, 1, 0, 1, 0, 0, 2, 2, 0, 1, 1, 2, 1, 0, 2, 1, 0, 2, 2, 0, 0, 2,
       2, 1, 1, 2, 1, 1, 0, 1, 0, 0, 2, 1, 1, 0, 2, 0, 2, 2, 2, 1, 1, 1,
       2, 1, 2, 1, 1, 2, 1, 1, 1, 0, 2, 2, 1, 1, 0, 1, 0, 2, 1, 0, 2, 2,
       0, 0, 2, 0, 1, 0, 1, 2, 0, 1, 1, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0,
       2, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 0, 0, 0, 1, 2, 2, 2,
       1, 0, 2, 1, 2, 1, 0, 1, 2, 2, 2, 0, 2, 0, 1, 1, 2, 1, 2, 2, 0, 0,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 0, 2, 2, 2, 1, 1, 1, 1, 2, 2,
       2, 0, 1, 2, 1, 0, 0, 1, 0, 0, 2, 1, 0, 2, 0, 1, 0, 0, 0, 1, 2, 2,
       1, 1, 0, 0, 1, 0, 2, 0, 2, 1, 2, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 0,
       1, 0, 0, 0, 2, 2, 2, 2, 1, 0, 2, 2, 1, 0, 0, 1, 1, 1, 0, 0, 2, 2,
       0, 2, 0, 0, 1, 2, 1, 2, 1, 0, 2, 0, 0, 0, 0, 0, 2, 1, 2, 1, 2, 0,
       0, 2, 1, 2, 1, 1, 0, 0, 2, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0, 2, 1, 1,
       0, 0, 0, 1, 0, 0, 2, 1, 1, 2, 1, 0, 0, 2, 1, 2, 0, 2, 0, 2, 1, 1,
       2, 1, 0, 2, 2, 0, 0, 1])

In [8]:
#label_encoder.transform(xtest)
'''y should be a 1D array,
got an array of shape(200,3) instead.
'''

'y should be a 1D array,\ngot an array of shape(200,3) instead.\n'

ORDINAL ENCODER

In [9]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
updated_xtrain = encoder.fit_transform(xtrain)
#updated_xtrain = encoder.fit_transform(xtrain['color'])
''' error '''
updated_xtrain

array([[1., 2., 2.],
       [0., 1., 0.],
       [0., 2., 2.],
       ...,
       [0., 0., 1.],
       [0., 2., 1.],
       [1., 2., 1.]], shape=(800, 3))

In [10]:
encoder.get_feature_names_out()

array(['color', 'size', 'material'], dtype=object)

In [11]:
#updated_xtest = encoder.transform(xtest)
#new_input=[['red1','large2','plastic'],['purple','extra large','wood']]
#encoder.transform(new_input)
#above we have entered data which isnt in the dataframe

#to handle unknown 
encoder = OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)

updated_xtrain = encoder.fit_transform(xtrain)
updated_xtest = encoder.fit_transform(xtest)
#new_data = [['white','small','wood'],['red','small','wood']] we got warning , its a 2d array , here they dont have a valid feature name
new_data = pd.DataFrame(data=[['white','small','wood'],['red','small','wood']] , columns= ['color','size','material']) #here no warning will be displayed
                        # both new_data can be used , its crt , but to avoid the warning we use 2nd new_data code 
updated_new_data = encoder.transform(new_data)
updated_new_data

array([[-1.,  2.,  2.],
       [ 2.,  2.,  2.]])

27/06/2026

In [12]:
'''
encoder = OrdinalEncoder(categories=[['green','blue','red']],handle_unknown='use_encoded_value',unknown_value=-1)
encoder.fit_transform(xtrain)

ValueError: Shape mismatch: 
if categories is an array, it has to be of shape (n_features,).
why?
xtrain is having 3 cols and categories=[[col_order]]
shape mismatched

when xtrain cols == col_orders

'''

"\nencoder = OrdinalEncoder(categories=[['green','blue','red']],handle_unknown='use_encoded_value',unknown_value=-1)\nencoder.fit_transform(xtrain)\n\nValueError: Shape mismatch: \nif categories is an array, it has to be of shape (n_features,).\nwhy?\nxtrain is having 3 cols and categories=[[col_order]]\nshape mismatched\n\nwhen xtrain cols == col_orders\n\n"

In [13]:
#encoder = OrdinalEncoder(categories=[['green','blue','red'],['small','medium','large'],
                                #['wood','plastic','metal']],handle_unknown='use_encoded_value')
#TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.
#encoder.fit_transform(xtrain[['color','size']])
'''ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).'''

encoder = OrdinalEncoder(categories=[['green','blue','red'],['small','medium','large'],['wood','plastic','metal']],handle_unknown='use_encoded_value',unknown_value=-1)
encoder.fit_transform(xtrain)

array([[0., 0., 0.],
       [1., 1., 2.],
       [1., 0., 0.],
       ...,
       [1., 2., 1.],
       [1., 0., 1.],
       [0., 0., 1.]], shape=(800, 3))

In [14]:
encoder = OrdinalEncoder(categories=[['green','blue','red'],['small','medium','large'],['wood','plastic','metal']],handle_unknown='use_encoded_value',unknown_value=-1)
encoder.fit_transform(xtrain)

array([[0., 0., 0.],
       [1., 1., 2.],
       [1., 0., 0.],
       ...,
       [1., 2., 1.],
       [1., 0., 1.],
       [0., 0., 1.]], shape=(800, 3))

In [15]:
encoder.transform(xtest)

array([[2., 0., 2.],
       [2., 0., 2.],
       [1., 0., 2.],
       [0., 0., 1.],
       [1., 1., 2.],
       [2., 2., 1.],
       [0., 2., 1.],
       [2., 0., 1.],
       [2., 2., 2.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 2., 2.],
       [2., 2., 1.],
       [1., 1., 0.],
       [0., 0., 2.],
       [2., 2., 2.],
       [0., 1., 0.],
       [2., 2., 1.],
       [2., 2., 0.],
       [1., 2., 2.],
       [0., 2., 2.],
       [0., 1., 2.],
       [0., 0., 1.],
       [1., 1., 1.],
       [2., 1., 1.],
       [1., 1., 0.],
       [0., 2., 2.],
       [2., 0., 2.],
       [1., 0., 2.],
       [0., 1., 1.],
       [2., 1., 2.],
       [2., 2., 0.],
       [1., 0., 2.],
       [0., 0., 2.],
       [1., 1., 2.],
       [1., 2., 0.],
       [2., 0., 0.],
       [2., 1., 1.],
       [2., 1., 2.],
       [0., 2., 2.],
       [2., 0., 0.],
       [2., 1., 0.],
       [0., 2., 2.],
       [2., 2., 1.],
       [1., 2., 1.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 1.],
       [0., 2., 0.],
       [1., 2., 0.],
       [1., 0., 2.],
       [2., 0., 0.],
       [1., 0., 0.],
       [1., 0., 2.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 2., 2.],
       [2., 2., 1.],
       [1., 1., 0.],
       [1., 2., 2.],
       [0., 0., 1.],
       [2., 1., 0.],
       [2., 0., 0.],
       [0., 0., 1.],
       [2., 1., 2.],
       [2., 0., 1.],
       [0., 1., 1.],
       [2., 2., 2.],
       [0., 2., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 2.],
       [0., 1., 1.],
       [0., 1., 0.],
       [1., 2., 1.],
       [0., 2., 1.],
       [1., 0., 1.],
       [0., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [2., 2., 2.],
       [1., 0., 1.],
       [1., 0., 1.],
       [2., 1., 2.],
       [0., 2., 2.],
       [1., 0., 0.],
       [2., 0., 2.],
       [1., 2., 0.],
       [2., 2., 0.],
       [2., 2., 1.],
       [1., 2., 2.],
       [2., 2., 0.],
       [1., 1., 2.],
       [0., 1., 2.],
       [2., 2., 0.],
       [1., 0., 1.],
       [1., 2., 2.],
       [0., 1., 0.],
       [1., 1., 0.],
       [2., 2., 2.],
       [1., 1., 1.],
       [1., 2., 2.],
       [2., 0., 0.],
       [0., 1., 1.],
       [2., 2., 1.],
       [2., 2., 2.],
       [2., 2., 0.],
       [2., 0., 1.],
       [1., 2., 0.],
       [1., 2., 0.],
       [2., 2., 0.],
       [0., 0., 1.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 1., 0.],
       [1., 2., 1.],
       [2., 0., 0.],
       [2., 1., 1.],
       [2., 1., 1.],
       [0., 2., 1.],
       [1., 2., 2.],
       [2., 0., 2.],
       [1., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 0., 0.],
       [2., 0., 2.],
       [2., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 1., 0.],
       [1., 2., 1.],
       [2., 1., 0.],
       [1., 2., 2.],
       [2., 1., 2.],
       [0., 1., 1.],
       [0., 0., 0.],
       [0., 0., 2.],
       [1., 2., 0.],
       [2., 2., 2.],
       [2., 2., 0.],
       [2., 2., 2.],
       [1., 2., 0.],
       [0., 2., 0.],
       [2., 0., 1.],
       [2., 0., 0.],
       [1., 2., 1.],
       [0., 0., 0.],
       [1., 1., 0.],
       [2., 1., 0.],
       [2., 1., 0.],
       [2., 2., 0.],
       [1., 2., 2.],
       [1., 0., 2.],
       [2., 1., 1.],
       [2., 1., 0.],
       [0., 2., 1.],
       [0., 1., 2.],
       [0., 1., 1.],
       [2., 2., 1.],
       [1., 1., 1.],
       [2., 0., 2.],
       [0., 1., 2.],
       [2., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 2., 1.],
       [1., 2., 0.],
       [1., 1., 2.],
       [2., 0., 0.],
       [2., 1., 2.],
       [1., 1., 2.],
       [2., 1., 1.],
       [1., 2., 1.],
       [2., 0., 2.],
       [2., 0., 0.],
       [0., 0., 2.],
       [1., 2., 2.],
       [0., 0., 1.],
       [0., 1., 2.],
       [1., 2., 2.],
       [1., 0., 2.],
       [1., 1., 2.],
       [2., 1., 2.],
       [1., 1., 0.],
       [1., 2., 0.],
       [2., 0., 0.],
       [2., 0., 1.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 0., 2.],
       [0., 0., 1.],
       [0., 1., 1.]])

TARGET ENCODER

In [16]:
from category_encoders import target_encoder
#encoder = TargetEncoder(cols=['color'],handel_unknown ='value') 
#cols we can use when we have mixed of column type like obj , numerical 
#above cols = color means its converts only color col into numeric
encoder = TargetEncoder()  # converts all the categorical into numerical col
encoder.fit_transform(xtrain,ytrain)

          color        size    material
29   253.164751  263.081784  245.481013
535  256.408397  254.923077  264.018248
695  256.408397  263.081784  245.481013
557  263.678700  263.081784  262.193772
836  253.164751  255.546512  262.193772
..          ...         ...         ...
106  263.678700  255.546512  262.193772
270  263.678700  263.081784  262.193772
860  256.408397  255.546512  262.193772
435  256.408397  263.081784  262.193772
102  253.164751  263.081784  262.193772

[800 rows x 3 columns]

In [17]:
#obj_cols = [] # wrong
obj_cols = xtrain.select_dtypes(include='object').columns
num_cols = xtrain.select_dtypes(include='number').columns

In [19]:
'''new_input = [['red','small','wood1']] 
encoder.transform(new_input)
#KeyError: 'color' 
if we pass [['red','small','wood1']] this , it doesnt understand which col is color , vch is size and vch is materail 
so to avoid this error we will pass in dict by specifing its col name'''

new_input = pd.DataFrame({
    'color' : ['red'],'size':['small'],'material':['wood']
})
encoder.transform(new_input)

      color        size    material
0  263.6787  263.081784  245.481013